//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCOdev.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kategoriler
    {
        public int kategoriID { get; set; }
        public string kategoriAd { get; set; }
        public string kategoriAciklama { get; set; }
        public Nullable<int> urunID { get; set; }
    
        public virtual Urunler Urunler { get; set; }
    }
}
