//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3DProject.Models.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTable
    {
        public int productID { get; set; }
        public int userID { get; set; }
        public Nullable<int> productCategoryID { get; set; }
        public string productName { get; set; }
        public string productDescription { get; set; }
        public string productImage { get; set; }
        public System.DateTime productAddDate { get; set; }
        public Nullable<int> productLikeId { get; set; }
    
        public virtual ProductCategoryTable ProductCategoryTable { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
