//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3DProject.Models.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserTable()
        {
            this.BlogTable = new HashSet<BlogTable>();
            this.ProductTable = new HashSet<ProductTable>();
            this.UserRoleTable = new HashSet<UserRoleTable>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string EmailAddress { get; set; }
        public string Password { get; set; }
        public string ActivationCode { get; set; }
        public bool IsEnabled { get; set; }
        public Nullable<int> kapakID { get; set; }
        public Nullable<int> likeID { get; set; }
        public Nullable<int> logID { get; set; }
        public Nullable<int> blogID { get; set; }
        public Nullable<int> pictureID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlogTable> BlogTable { get; set; }
        public virtual KapakPictureTable KapakPictureTable { get; set; }
        public virtual LogTable LogTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductTable> ProductTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRoleTable> UserRoleTable { get; set; }
        public virtual PictureTable PictureTable { get; set; }
    }
}
