/*    ==Scripting Parameters==

    Source Server Version : SQL Server 2016 (13.0.4001)
    Source Database Engine Edition : Microsoft SQL Server Enterprise Edition
    Source Database Engine Type : Standalone SQL Server

    Target Server Version : SQL Server 2016
    Target Database Engine Edition : Microsoft SQL Server Enterprise Edition
    Target Database Engine Type : Standalone SQL Server
*/

USE [master]
GO

/****** Object:  Database [odevDb]    Script Date: 28.09.2017 13:15:12 ******/
CREATE DATABASE [odevDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'odevDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\odevDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'odevDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\odevDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [odevDb] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [odevDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [odevDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [odevDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [odevDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [odevDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [odevDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [odevDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [odevDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [odevDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [odevDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [odevDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [odevDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [odevDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [odevDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [odevDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [odevDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [odevDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [odevDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [odevDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [odevDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [odevDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [odevDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [odevDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [odevDb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [odevDb] SET  MULTI_USER 
GO

ALTER DATABASE [odevDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [odevDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [odevDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [odevDb] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [odevDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [odevDb] SET QUERY_STORE = OFF
GO

USE [odevDb]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [odevDb] SET  READ_WRITE 
GO


